### ISSUE TITLE
i want  to  learn the app use for  my graduation thesis

### ISSUE THREAD

**Issue by windli93** [italankin/dictionary#1]
some question will  ask for you,can you help me?

**Comment by italankin** [comment]
Sure, I will try to answer any questions.

**Comment by windli93** [comment]
I compiling the android project use Intellj Idea , but compiler tool tell me some error information.
Like this path error : import com.italankin.dictionary.BuildConfig, the project can't hava this java class and I  don't know create the class how to write code in this class.

**Comment by windli93** [comment]
Another question in debug.propertis, can you give me a usable testing account ? I am located in china . You know,  GFW  hinding too many  website , I have to put forward to this request  that trouble to you.

**Comment by windli93** [comment]
Oh, R.java file missing, I  don't know how to do. But your's code is artful.

**Comment by italankin** [comment]
**BuildConfig** class, as well as **R**, are automatically generated files, you must not create them by hand. If they wasn't generated, then there must be some errors in the source code or configuration. Can you provide more information about errors you're getting?

If you haven't made any changes, project should compile without any errors. Also, **debug.properties** contains a valid API key, so, if you build debug version you will get a properly working application.

Try to build debug version, run `./gradlew clean assembleDebug` from the project's root, it might solve the problems.

You can also modify [`app/build.gradle`](https://github.com/italankin/dictionary/blob/develop/app/build.gradle) by adding these lines to the [`android`](https://github.com/italankin/dictionary/blob/develop/app/build.gradle#L3) block:

```
lintOptions {
    abortOnError false
}
```

then try to build project.

**Comment by windli93** [comment]
@italankin OK，I will try to  solve these errors  found by your  suggest  when i  back to live  house.

**Comment by windli93** [comment]
![2016-04-09 00-12-071](https://cloud.githubusercontent.com/assets/16792321/14390101/0028fe56-fde8-11e5-9250-d9c4b5cc380e.png)
you can watch picture , some jar package can't import . my android sdk version is 23

**Comment by windli93** [comment]
![2016-04-09 00-17-31](https://cloud.githubusercontent.com/assets/16792321/14390207/905e1e70-fde8-11e5-9d4d-36c7cdbf9853.png)

These problem was same , jar package  not import and  R.java class file , Configure file   inexistenced. 

![2016-04-09 00-18-01](https://cloud.githubusercontent.com/assets/16792321/14390352/0ee11f90-fde9-11e5-911e-d895c2b500c9.png)

**Comment by windli93** [comment]
These code   have error information , compiler  tools  remaid me pass value to these option.
signingConfigs {
        debug {
            storeFile file(DEBUG['keystore'])
            storePassword DEBUG['keystorePasswd']
            keyAlias DEBUG['alias']
            keyPassword DEBUG['aliasPasswd']
        }
        release {
            if (RELEASE != null) {
                storeFile file(RELEASE['keystore'])
                storePassword RELEASE['keystorePasswd']
                keyAlias RELEASE['alias']
                keyPassword RELEASE['aliasPasswd']
            }
        }
    }

**Comment by ragrok** [comment]
These code have error information , compiler tools remaid me pass value to these option.
`signingConfigs {
        debug {
            storeFile file(DEBUG['keystore'])
            storePassword DEBUG['keystorePasswd']
            keyAlias DEBUG['alias']
            keyPassword DEBUG['aliasPasswd']
        }
        release {
            if (RELEASE != null) {
                storeFile file(RELEASE['keystore'])
                storePassword RELEASE['keystorePasswd']
                keyAlias RELEASE['alias']
                keyPassword RELEASE['aliasPasswd']
            }
        }
    }`

**Comment by italankin** [comment]
Signing configuration is not an issue, unless you're trying to build release version of application.

Open terminal in Intellij IDEA (by default shorcut is `Alt+F12`), then execute this command:

```
./gradlew clean assembleDebug
```

Then show me the full output of the command.

**Comment by italankin** [comment]
OK, for some point Intellij Idea is working differently from Android Studio.

At first, open [Project Structure Dialog](https://www.jetbrains.com/help/idea/15.0/project-structure-dialog.html) and under _Project SDK_ select Android (you need API 23) from list, or click _New..._ and select your Android SDK directory. Click OK on all windows, it should resolve all _missing class_ issues.

Then, download the file (`Fix.txt`) I attached, head to Intellij and under VCS menu select _Apply patch..._. Search for a file you downloaded and click OK. This will apply necessary changes to _build.gradle_ file and enable Intellij build project.

[Fix.txt](https://github.com/italankin/dictionary/files/210690/Fix.txt)

**Comment by windli93** [comment]
I add  a new andorid project with Intellij Idea , it's can solve problem that not have R.java file and configure.java file. next, I  changed android  support dependices , old vesion is 23.0.1 ,new version is 24.0.0.

**Comment by windli93** [comment]
I will add java code and  other files to project by hands.

**Comment by windli93** [comment]
finally , I  downing andorid studio on  the Internet . Choose  usb device  as Target , then running app  on my xiaomi phone success. after days , I will  read source and  understand it .

**Comment by windli93** [comment]
![screenshot_2016-04-09-17-25-30_com italankin dictionary](https://cloud.githubusercontent.com/assets/16792321/14402990/61f7add6-fe78-11e5-9310-d9c5c21c2d21.png)
