### ISSUE TITLE
How to use only ru-eng?

### ISSUE THREAD

**Issue by eraliev** [italankin/dictionary#2]
Hi how to use only from ru to eng?

**Comment by italankin** [comment]
Hello,

Go to the Settings (which is accessible from three-dot menu).
The first switch (Lookup in both directions) is what you want.

**Comment by eraliev** [comment]
Здравствуйте )) а как использовать только один язык например с казахского на русский и английский?

**Comment by italankin** [comment]
Что имеется в виду под "использовать только один язык"?
